### ISSUE TITLE
The script infinitely archives the home directory

### ISSUE THREAD

**Issue by Nioctris** [nathaneltitane/dextop#28]
It happens at the beginning of the script. I literally left it running overnight, but nothing changed. Can I just skip it? Termux is installed last, I completely reinstalled it before using the script.

**Comment by nathaneltitane** [comment]
Hello @Nioctris , the intentional backup of the home directory is in fact a wanted behavior.

Can you give me more details on your home directory contents? Is it possible that you had very large files in there?

As far as I can tell, I have run that routine several times before implementing it: it has always been successful in finishing and the rest of the setup continuing.

I will have a look at it again.

**Comment by nathaneltitane** [comment]
@Nioctris Issue has been resolved: the problem came from frobulator - there was typo on the process identification which prevented the functions calling frobulator.process or frobulator.progress to continue on PID close.

Feel free to start over or simply clear $HOME/.local/bin and see what happens
